version: '3.1'

services:
  db: 
    image: mysql
    healthcheck:
      test: "exit 0"
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=mypassword
      - MYSQL_DATABASE=ecom
    container_name: ecom-mysql-database
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    container_name: adminer-mysql
    ports:
      - 8080:8080
volumes:
  db_data: 